version: '3.8'
services:
  api:
    container_name: news-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes :
      - ./backend:/app
    command: 'php artisan serve --host=0.0.0.0'
    tty: true
    depends_on:
      - postgres
    ports:
      - 8000:8000

  postgres:
      container_name: news-db
      image: postgres:latest
      ports:
          - "5432:5432"
      environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          PGDATA: /var/lib/postgresql/data
          
  frontend:
    container_name: news-ui
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    command: npm run dev
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development

networks:
  news:
    driver: bridge